export const GLOBAL_PREFIX = 'api';

export const ENV_VARIABLE_NAMES = {
  ACCESS_TOKEN_EXPIRATION_TIME: 'ACCESS_TOKEN_EXPIRATION_TIME',
  DB_NAME: 'DB_NAME',
  EMAIL_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS:
    'EMAIL_CONFIRMATION_CODE_EXPIRATION_TIME_IN_HOURS',
  EMAIL_BLOG_PLATFORM: 'EMAIL_BLOG_PLATFORM',
  EMAIL_BLOG_PLATFORM_PASSWORD: 'EMAIL_BLOG_PLATFORM_PASSWORD',
  EMAIL_SERVICE: 'EMAIL_SERVICE',
  INCLUDE_TESTING_MODULE: 'INCLUDE_TESTING_MODULE',
  IS_SWAGGER_ENABLED: 'IS_SWAGGER_ENABLED',
  IS_USER_AUTOMATICALLY_CONFIRMED: 'IS_USER_AUTOMATICALLY_CONFIRMED',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  ADMIN_USERNAME: 'ADMIN_USERNAME',
  MONGO_URL: 'MONGO_URL',
  NODE_ENV: 'NODE_ENV',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  PORT: 'PORT',
  RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS:
    'RECOVERY_CODE_EXPIRATION_TIME_IN_HOURS',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
} as const;

export enum ENVIRONMENTS {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
  TESTING = 'testing',
}
